### ISSUE TITLE
debug problem

### ISSUE THREAD

**Issue by lyqacc** [lyandut/SmartMPW#1]
尊敬的作者：
您好！我们在调试代码时出现了数组溢出的问题，

在AdaptSelect.hpp中的for循环（如下）设置断点，代码跑了几步就跳出，出现：vector subscript out of range 的error，请作者指教。

// 分支初始化iter=1
		// 单线程
		for (coord_t bin_width : candidate_widths) {
			cw_objs.push_back({ bin_width, 1, unique_ptr<MpwBinPack>(
				new MpwBinPack(_ins.get_polygon_ptrs(), bin_width, INF, _gen)) });
			cw_objs.back().mbp_solver->random_local_search(1);
			check_cwobj(cw_objs.back());
		}

**Comment by lyandut** [comment]
可以提供更多的信息帮助我复现问题吗？
我这边所有算例都可以正常跑的。。。

**Comment by lyqacc** [comment]
作者您好：
我的问题大约就是如下：
1，我在生成的时候，出现还原包错误，不知道是什么原因，或者您的代码有什么配置环境吗？
2，运行调试的时候，在算法中的一个循环中运行几次就会报错
我的错误截图在附件，然后我将我在github上下载的开源代码打包在附近，不知道这份代码是否有问题，感谢您在百忙中回复！


&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "lyandut/SmartMPW"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年11月10日(星期三) 下午5:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [lyandut/SmartMPW] debug problem (Issue #1)





 
可以提供更多的信息帮助我复现问题吗？
 我这边所有算例都可以正常跑的。。。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android. 


从QQ邮箱发来的超大附件

smartmpw.zip (65.92M, 2021年12月10日 18:24 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?t=exs_ftn_download&k=25383964e076d199680bc0201430024d070c0e060b515451490d5b51501d0455515b14065005514f065c0805505455535d5c5a02323c301109594b105f40474c1e5149640f&code=d89d200b

**Comment by lyandut** [comment]
1. NuGet 包还原失败是因为使用vcpkg安装了boost，忽略即可，或者卸载Checker项目。
2. [修复merge后skyline_index失效的bug](https://github.com/lyandut/SmartMPW/commit/6f7529b129983ad2d5da0791ba576c6d227b4143)
